import { Router } from 'express';
import authRoutes        from './auth.routes';
import coursesRoutes     from './courses.routes';
import batchesRoutes     from './batches.routes';
import dashboardRoutes   from './dashboard.routes';
import trainersRoutes    from './trainers.routes';
import learnersRoutes    from './learners.routes';
import modulesRoutes     from './modules.routes';
import quizzesRoutes     from './quizzes.routes';
import assignmentsRoutes  from './assignments.routes';
import assessmentsRoutes  from './assessments.routes';
import attendanceRoutes  from './attendance.routes';
import maintenanceRoutes from './maintenance.routes';
import permissionsRoutes from './permissions.routes';
import userPermissionsRoutes from './user-permissions.routes';
import rolesRoutes from './roles.routes';
import chatRoutes from './chat.routes';
import sessionsRoutes from './sessions.routes';
import feesRoutes from './fees.routes';
import recordingsRoutes from './recordings.routes';
import programsRoutes from './programs.routes';
import codingRoutes from './coding.routes';
import feesV2Routes from './fees-v2.routes';
import paymentRoutes from './payment.routes';
import invoicesRoutes from './invoices.routes';
import messagingRoutes from './messaging.routes';
import mockInterviewsRoutes from './mock_interviews.routes';
import placementRoutes from './placement.routes';
import feedbackRoutes from './feedback.routes';
import grievancesRoutes from './grievances.routes';
import githubWebhookRoutes from './github.webhook.routes';
import internRoutes from './intern.routes';
import analyticsRoutes from './analytics.routes';
const router: import("express").Router = Router();

router.use("/webhooks/github", githubWebhookRoutes);
router.use("/auth", authRoutes);
router.use("/courses", coursesRoutes);
router.use("/courses/:courseId/modules", modulesRoutes);
router.use("/batches",     batchesRoutes);
router.use("/dashboard",   dashboardRoutes);
router.use("/trainers",    trainersRoutes);
router.use("/learners",    learnersRoutes);
router.use("/quizzes",     quizzesRoutes);
router.use("/assignments",  assignmentsRoutes);
router.use("/assessments", assessmentsRoutes);
router.use("/attendance",  attendanceRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/permissions", permissionsRoutes);
router.use("/user-permissions", userPermissionsRoutes);
router.use('/roles', rolesRoutes);
router.use('/chat', chatRoutes);
router.use("/student", sessionsRoutes);
router.use("/fees", feesRoutes);
router.use("/recordings", recordingsRoutes);
router.use("/programs", programsRoutes);
router.use("/coding", codingRoutes);
router.use("/fees-v2", feesV2Routes);
router.use("/payments", paymentRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/messaging", messagingRoutes);
router.use("/interviews", mockInterviewsRoutes);
router.use("/placements", placementRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/grievances", grievancesRoutes);
router.use("/intern",    internRoutes);
router.use("/analytics", analyticsRoutes);
export default router;
